maintainer: Dhanoop Karunakaran
debug: True
GOOGLE_API:
  scopes:
    - 'https://mail.google.com/'
    - 'https://www.googleapis.com/auth/tasks'
    - 'https://www.googleapis.com/auth/drive'

GMAIL_AGENT:
  recursion_limit: 10
  verbose: False

BROWSER_AGENT:
  recursion_limit: 10
  verbose: False

SUPERVISOR:
  recursion_limit: 10
